<style>
    .block-cart , .block-compare , .block-reorder
    {
        display:none;
    }
    .block-anav
    {
        display:none;
    }
    .form-list label {
        float: left;
        color: #666;
        font-weight: 400;
        position: relative;
        z-index: 0;
        line-height: 2;
    }
    .page-title {
        border-bottom: 1px solid #eaeaea;
        display: block;
    }
    .page-title h1
    {
        color:#1e9093
    }
    .data-table td {
        padding: 30px 8px;
    }
    .data-table thead th {
        font-weight: normal;
        border-right: 0;
        padding: 30px 8px;
        text-align: center;
        color: #333;
        white-space: nowrap;
        vertical-align: middle;
    }
    .data-table thead th {
        border-top: 0;
        border-bottom: 0;
        text-transform: capitalize;
        color:#fff;
    }
    .data-table {
        width: 100%;
        border: 0;
    }
    .data-table tbody th, .data-table tbody td {
        border-bottom: 1px solid #ddd;
        border-right: 0;
    }
    caption, th, td {
        vertical-align: middle;
        text-align: center;
        font-weight: normal;
    }
    .data-table thead {
        background-color: #1e9093;
    }
</style>
<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magento.com for more information.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
    <table class="data-table" id="my-orders-table">
        <col width="1" />
        <col width="1" />
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Ship To') ?></th>
            <th><?php echo $this->__('Weight Diff. Refund') ?></th>
            <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
            <tr>
                <td><?php echo $_order->getRealOrderId() ?></td>
                <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                <td><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                <td><?php echo $_order->formatPrice(abs($_order->getWmsRefund())) ?></td>
                <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                <td><em><?php echo $_order->getStatusLabel() ?></em></td>

                <td class="a-center">
                <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                    <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                    <?php if($_order->getStatusLabel() == 'Delivered') { ?>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span class="separator">|</span>
                            <a href="<?php echo Mage::getBaseUrl();?>rma/order/completed/" class="link-reorder"><?php echo $this->__('Refund') ?></a>
                        <?php endif ?>
                    <?php } ?>   </span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table');</script>
    <?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
